version: '3'

services:
  nginx:
    container_name: nginx
    build:
        context: ./requirements/nginx
        dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - wordpress
    networks:
      - my_network

  wordpress:
    container_name: wordpress
    build:
        context: ./requirements/wordpress
        dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: examplepass
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - my_network

networks:
  my_network: